######################################################
##                                                  ##
##                  SSB - OneBlock                  ##
##                Developed by Ome_R                ##
##                                                  ##
######################################################

# Where should the one-block be?
# That's the offset from the center of the new island.
block-offset: -0.5, -1, -0.5

# How should the timer between phases be formatted?
# This section can support multiple lines.
timer-format: '&6{0}'

# Set the hierarchy of the phases
phases:
  - '2000      @   0-plains-phase.json'
  - '4000      @   1-underground-phase.json'
  - '6000      @   2-snow-phase.json'
  - '8000      @   3-ocean-phase.json'
  - '10000     @   4-jungle-phase.json'
  - '12000     @   5-red-desert-phase.json'
  - '14000     @   6-nether-phase.json'
  - '16000     @   7-idyll-phase.json'
  - '18000     @   8-desolate-phase.json'
  - '20000     @   9-end-phase.json'
  - '100000    @   10-poor-phase.json'

# Should /is oneblock will be injected into SuperiorSkyblock?
# This command is identical to /oneblock check.
# The permission for using the command will be superior.island.oneblock
inject-island-command: true

# List of schematics that will be used for one-block.
# If you want all schematics to work, set this list to `whitelisted-schematics: []`
whitelisted-schematics: []

# How should the module save data?
# Use 'SQL' or 'FLAT'.
# Warning: Changing this value mid-session will cause data to be lost.
data-type: FLAT

# When enabled, people that finish the last phase will be back to phase 1, starting over again.
phases-loop: false

# Whether OneBlock can be interacted with pistons.
# When true, players will be able to move the OneBlock using pistons.
piston-interaction: true